name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      POLICYENGINE_US_DATA_GITHUB_TOKEN: ${{ secrets.POLICYENGINE_US_DATA_GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: make docker

      - name: Run docker image
        run: docker run policyengine-us-data:latest
      
