name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make test
  evaluate:
    name: Evaluate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: make install

      - name: Create report
        run: python policyengine_us/evaluation/report.py --output report.md
      
      - name: Install current repo version
        run: pip install git+https://github.com/policyengine/policyengine-us-data
      
      - name: Create legacy report
        run: python policyengine_us/evaluation/report.py --output legacy_report.md
      
      - name: Get diff
        run: git diff --no-index -- report.md legacy_report.md > diff.md
      
