name: Pull request

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'PolicyEngine/policyengine-us-data')
      && (github.event.head_commit.message == 'Update PolicyEngine US data')
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Check formatting
        run: black . -l 79 --check
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'PolicyEngine/policyengine-us-data')
      && !(github.event.head_commit.message == 'Update PolicyEngine US data')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Build changelog
        run: pip install "yaml-changelog>=0.1.7" && make changelog
      - name: Preview changelog update
        run: ".github/get-changelog-diff.sh"
      - name: Check version number has been properly updated
        run: ".github/is-version-number-acceptable.sh"
      - name: Update changelog
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          committer_name: Github Actions[bot]
          author_name: Github Actions[bot]
          message: Update PolicyEngine US data
          github_token: ${{ secrets.POLICYENGINE_GITHUB }}
  test:
    name: Build and test
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'PolicyEngine/policyengine-us-data')
      && (github.event.head_commit.message == 'Update PolicyEngine US data')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install package
        run: pip install -e ".[dev]"
      - name: Download data inputs
        run: make download
        env:
          POLICYENGINE_US_DATA_GITHUB_TOKEN: ${{ secrets.POLICYENGINE_US_DATA_GITHUB_TOKEN }}
      - name: Build datasets
        run: make data
        env:
          TEST_LITE: true
      - name: Run tests
        run: pytest
      - name: Test documentation builds
        run: make documentation